version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_java
    command: ["mongod", "--tlsMode", "requireTLS", "--tlsCertificateKeyFile", "/etc/ssl/server.pem", "--tlsCAFile", "/etc/ssl/ca.crt"]
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./ssl:/etc/ssl:ro

volumes:
  mongodb_data:
    driver: local